abi_svr4-objs	:= hrtsys.o ioctl.o ipc.o mmap.o open.o svr4.o sysconf.o \
		   sysfs.o sysinfo.o sysi86.o ulimit.o utsname.o stream.o \
		   stat.o socksys.o signal.o misc.o socket.o statvfs.o \
		   fcntl.o filio.o termios.o consio.o tapeio.o sockio.o \
		   timod.o xti.o

obj-m	+= abi_svr4.o

include $(ABI_DIR)/SETFLG
